language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
cache: pip
matrix:
  fast_finish: true
# commands to install dependencies
before_install:
  # If python version is < 3, then don't run BamQC module
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sed -i '/bamqc/d' setup.py docs/README.md multiqc/utils/config_defaults.yaml; fi
install:
  - python setup.py install
  - git clone https://github.com/ewels/MultiQC_TestData.git test_data
  - cd test_data
  - mkdir empty_dir
# commands to run tests
script:
  - python -m unittest discover
  - multiqc data --ignore data/modules/
  - multiqc --lint data/modules/
  - multiqc --lint data/modules/ -m fastqc -f -d -dd 1 -i "Forced Report" -b "This command has lots of options" --filename custom_fn --no-data-dir
  - multiqc --lint data/modules/ -f --flat --tag methylation --exclude clusterflow --ignore-samples ngi --fullnames --zip-data-dir -c ../multiqc_config_example.yaml
  - multiqc -m star -o tests/multiqc_report_dev -t default_dev -k json --file-list data/special_cases/file_list.txt
  - multiqc -f empty_dir
  - multiqc -f data/modules/gatk/BaseRecalibrator/recal_data.table
